name: Update Docker Hub Description

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - '.github/workflows/docker-description.yml'

env:
  DOCKERHUB_REPO: 'maateen/docker-beanstalkd'

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
