name: Beanstalkd Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKERHUB_REPO: maateen/docker-beanstalkd
  GHCR_REPO: ghcr.io/maateen/docker-beanstalkd
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine_version: ["3.18", "3.19", "3.20", "3.21"]
        beanstalkd_version: ["v1.8", "v1.9", "v1.10", "v1.11", "v1.12", "v1.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        id: prep
        run: |
          echo "VERSION=${{ matrix.beanstalkd_version }}-alpine-${{ matrix.alpine_version }}" >> $GITHUB_ENV
          echo "IS_RELEASE=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Merge pull request') }}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}
            ${{ env.GHCR_REPO }}

      - name: Login to Docker Hub
        if: env.IS_RELEASE == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: env.IS_RELEASE == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.IS_RELEASE == 'true' }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
            BEANSTALKD_VERSION=${{ matrix.beanstalkd_version }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
            ${{ env.GHCR_REPO }}:${{ env.VERSION }}
            ${{ matrix.beanstalkd_version == 'v1.13' && matrix.alpine_version == '3.21' && format('{0}:latest,{1}:latest', env.DOCKERHUB_REPO, env.GHCR_REPO) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check image
        if: env.IS_RELEASE == 'true'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ env.VERSION }}
          docker buildx imagetools inspect ${{ env.GHCR_REPO }}:${{ env.VERSION }}
