name: Update Docker Hub Description

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
      - '.github/workflows/docker-description.yml'

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: maateen/docker-beanstalkd
          short-description: "A Docker container for Beanstalkd, a simple and fast general-purpose work queue."
          readme-filepath: ./README.md
