name: Test Docker Build

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine: ["3.17", "3.18", "3.19", "3.20"]
        beanstalkd: ["1.8", "1.9", "1.10", "1.11", "1.12", "1.13"]
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          build-args: ALPINE_VERSION=${{ matrix.alpine }} BEANSTALKD_VERSION=${{ matrix.beanstalkd }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          platforms: ${{ matrix.platform }}
          tags: ${{ matrix.beanstalkd }}-alpine-${{ matrix.alpine }}
